<?php
/**
 * UpdateWebhookTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * UpdateWebhookTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateWebhook
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateWebhookTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateWebhook"
     */
    public function testUpdateWebhook()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "fallback_url"
     */
    public function testPropertyFallbackUrl()
    {
    }

    /**
     * Test attribute "error_url"
     */
    public function testPropertyErrorUrl()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }

    /**
     * Test attribute "retry_attempts"
     */
    public function testPropertyRetryAttempts()
    {
    }
}
