<?php
/**
 * ActivityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ActivityApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ActivityApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for leadIdActivityEmailEmailIdDelete
     *
     * .
     *
     */
    public function testLeadIdActivityEmailEmailIdDelete()
    {
    }

    /**
     * Test case for leadIdActivityEmailEmailIdPut
     *
     * .
     *
     */
    public function testLeadIdActivityEmailEmailIdPut()
    {
    }

    /**
     * Test case for leadIdActivityEmailPost
     *
     * .
     *
     */
    public function testLeadIdActivityEmailPost()
    {
    }

    /**
     * Test case for leadIdActivityGet
     *
     * .
     *
     */
    public function testLeadIdActivityGet()
    {
    }

    /**
     * Test case for leadIdActivityNoteNoteIdDelete
     *
     * .
     *
     */
    public function testLeadIdActivityNoteNoteIdDelete()
    {
    }

    /**
     * Test case for leadIdActivityNoteNoteIdPut
     *
     * .
     *
     */
    public function testLeadIdActivityNoteNoteIdPut()
    {
    }

    /**
     * Test case for leadIdActivityNotePost
     *
     * .
     *
     */
    public function testLeadIdActivityNotePost()
    {
    }

    /**
     * Test case for leadIdActivitySmsPost
     *
     * .
     *
     */
    public function testLeadIdActivitySmsPost()
    {
    }

    /**
     * Test case for leadIdActivitySmsSmsIdDelete
     *
     * .
     *
     */
    public function testLeadIdActivitySmsSmsIdDelete()
    {
    }

    /**
     * Test case for leadIdActivitySmsSmsIdPut
     *
     * .
     *
     */
    public function testLeadIdActivitySmsSmsIdPut()
    {
    }
}
