<?php
/**
 * LeadContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Salestream API
 *
 * Salestream API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LeadContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LeadContactApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for leadIdContactsContactIdDelete
     *
     * .
     *
     */
    public function testLeadIdContactsContactIdDelete()
    {
    }

    /**
     * Test case for leadIdContactsContactIdGet
     *
     * .
     *
     */
    public function testLeadIdContactsContactIdGet()
    {
    }

    /**
     * Test case for leadIdContactsContactIdPut
     *
     * .
     *
     */
    public function testLeadIdContactsContactIdPut()
    {
    }

    /**
     * Test case for leadIdContactsGet
     *
     * .
     *
     */
    public function testLeadIdContactsGet()
    {
    }

    /**
     * Test case for leadIdContactsPost
     *
     * .
     *
     */
    public function testLeadIdContactsPost()
    {
    }
}
